# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbasite', '0002_player_allplayerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='allplayerdata',
        ),
        migrations.AddField(
            model_name='player',
            name='personalInfo',
            field=models.CharField(default='none', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='playerStats',
            field=models.CharField(default='none', max_length=2048),
            preserve_default=False,
        ),
    ]
