# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbasite', '0003_auto_20170712_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playerStats',
            new_name='PlayerCareerStats',
        ),
    ]
